name: Contador

on:
  push:
    branches: [ nibel ]
  pull_request:
    branches: [ nibel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.100-rc.2.20479.15"
    - name: Build Core
      run: dotnet build --configuration Debug ./src/Contador.Core/Core/Contador.Core.csproj
    - name: Build DAL.MySQL
      run: dotnet build --configuration Debug ./src/Contador.DAL/MySQL/Contador.DAL.MySQL.csproj
    - name: Build Contador
      run: dotnet build --configuration Debug ./src/Contador/Contador/Contador.csproj
    - name: Build WEB
      run: dotnet build --configuration Debug ./src/Contador.Web/Server/Contador.Web.Server.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/Contador/Tests/Contador.Tests.csproj
