name: Contador

on:
  push:
    branches: [ nibel ]
  pull_request:
    branches: [ nibel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.100-rc.2.20479.15"
    - name: Install dependencies
      run: dotnet restore ./src/Contador.sln
    - name: Build Core
      run: dotnet build --configuration Debug --no-restore ./src/Contador.Core/Core/Contador.Core.csproj
    - name: Build DAL
      run: dotnet build --configuration Debug --no-restore ./src/Contador.DAL/Contador.DAL.csproj
    - name: Build WEB
      run: dotnet build --configuration Debug --no-restore ./src/Contador.Web/Server/Contador.Web.Server.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/Contador.Web/Server.Tests/Contador.Web.Server.Tests.csproj
